name: Run GuardianAi pipeline on self-hosted aws runner

on:
  pull_request:
    push:
    branches: [main]
  workflow_dispatch:  


jobs:
  run-pipeline:
    runs-on: [self-hosted, clearml, yolo]   # must match the labels you set
    timeout-minutes: 6000   # 4 days + a safety margin 
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx
          sudo apt-get install -y libglib2.0-0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ClearML pipeline
        env:
          CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
          CLEARML_API_SECRET_KEY: ${{ secrets.CLEARML_API_SECRET_KEY }}
          CLEARML_API_HOST:     ${{ secrets.CLEARML_API_HOST }}
       

        run: |
          python Guardian_pipeline.py 